providers = ["...", "python", "node"]

[phases.setup]
    nixPkgs = ['...', 'libudev.h']

[phases.build]
# It's better practice to list commands separately
cmds = [
    "npm install",
]

[start]
cmd = "npm run start"

git commit -m "Refactor usability tests.

Co-authored-by: pkxro <solponomarev@gmail.com>"